title: QMK Configurator
email: adeonhy@gmail.com
show_downloads: true
description: QMK for potatoes - an open source configurator for QMK Firmware (only the AVR boards right now)
baseurl: "/qmk_configurator"
url: "http://adeonhy.github.io"
github_username: adeonhy
repository: adeonhy/qmk_configurator
theme: jekyll-theme-minimal
